MembershipSite/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin
admin.autodiscover()
import settings
from MembershipSite.logic.views import *

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'myproject.views.home', name='home'),
    # url(r'^myproject/', include('myproject.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/$', 'MembershipSite.logic.views.login'),
    url(r'^logout/$', 'MembershipSite.logic.views.logout'),
    url(r'^registration/$', 'MembershipSite.logic.views.registration'),
    url(r'^registration_completed/$', 'MembershipSite.logic.views.registration_completed'),
    url(r'^editprofile', 'MembershipSite.logic.views.editprofile'),
    url(r'^sendmail/$', 'MembershipSite.logic.views.send_testmail'),
    url(r'^confirm/(?P<code>[-a-z0-9]+)/$', 'MembershipSite.logic.views.confirm_registration', name='confirm_registration'),
    url(r'^', include('cms.urls')),
)

if settings.DEBUG:
    urlpatterns = patterns('',
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
    {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    url(r'', include('django.contrib.staticfiles.urls')),
) + urlpatterns

MembershipSite/logic/forms.py
from django import forms
from django.contrib.auth.models import User
from models import Profile, mail, TITLE_TYPES
from django.contrib.auth import authenticate

class SignupForm(forms.Form):
    '''
    This form is used for sign-up
    '''
    title = forms.ChoiceField(choices=TITLE_TYPES, label="Title")
    username = forms.CharField(max_length=20, label="User Name")
    email = forms.EmailField(label = 'Email')
    password = forms.CharField(max_length=16, label="Password", widget = forms.PasswordInput)
    confirm_password = forms.CharField(max_length=16, label="Password Again", widget = forms.PasswordInput)
    country = forms.CharField(max_length=100, label='Country')
    state = forms.CharField(max_length=20, label='State')
    city = forms.CharField(max_length=100, label='city')
    
    def __init__(self, selfdata=None, *args, **kw):
        super(SignupForm, self).__init__(*args, **kw)
        if not selfdata is None:
            self.fields['title'].initial = selfdata['title']
            self.fields['username'].initial = selfdata['username']
            self.fields['email'].initial = selfdata['email']
            self.fields['country'].initial = selfdata['country']
            self.fields['state'].initial = selfdata['state']
            self.fields['city'].initial = selfdata['city']
    
    def clean_email(self):
        '''
        check if email already exist in database
        '''
        d = self.cleaned_data
        email = d.get('email')
        if User.objects.filter(email__iexact=email).count():
            raise forms.ValidationError("Email address already exists in database.")
    
    def clean_username(self):
        '''
        check if username is already exist
        '''
        d = self.cleaned_data
        username = d.get('username')
        if User.objects.filter(username__iexact=username).count():
            raise forms.ValidationError("Username address already exists in database.")
    
    def clean_confirm_password(self):
        '''
        check if password and confirm password is same
        '''
        data = self.cleaned_data
        password = data.get('password')
        confirm_password = data.get('confirm_password')
        if password != confirm_password:
            raise forms.ValidationError('Password Confirmation FAILED!')
        #return confirm_password
    
    def save(self, data):
        '''
        This function creates new User with data
        '''
        email = data['email']
        username = data['username']
        password = data['password']
        u = User(username=username, email=email, is_active=True)
        u.set_password(password)
        u.save()
        profile = Profile(title=data['title'], user=u, country=data['country'], state=data['state'], city=data['city'])
        profile.save()
        return True
        #bellow code is for email verification, but it's not needed for now.
        #profile = Profile.create(u)
        #profile.save()
        #profile.send_email_confirmation_mail()
        #print "sent email"
        
class AuthenticationByEmailForm(forms.Form):
    '''
    This form is used for user authentication
    '''
    username = forms.CharField(label = "Username")
    password = forms.CharField(label = "Password", widget=forms.PasswordInput)
   
    ''' 
    def __init__(self, request=None):
        self.request = request
        self.user_cache = None
        self.username = None
        self.password = None
        super(AuthenticationByEmailForm, self).__init__()
    '''
        
    def clean(self):
        '''
        This function is automatically called when form.is_valid() function is called
        And authenticate user with username and password.
        '''
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        if username and password:
            user_cache = authenticate(username = username, password = password)
            if user_cache is None:
                raise forms.ValidationError("Please enter a correct email and password")
            elif not user_cache.is_active:
                raise forms.ValidationError("This account is not activated yet")
        return self.cleaned_data
    
    
    
    
    

MembershipSite/templates/base.html
{% load cms_tags sekizai_tags i18n menu_tags %}
<html>
<head>
	{% render_block "css" %}
	<style type="text/css">
		#header_wrapper{
			width : 100%;
			height : 100px;
			position: relative;
		}
	</style>
</head>
<body>
	<div id="header_wrapper">
		<span style="position:absolute; left:30px; bottom:30px;">
			Username: {{ request.user.username }},
			EmailAddress: {{request.user.email }}
		</span>
		<span style="position:absolute; right:30px; bottom: 30px;"> 
			<a href="/editprofile">Edit Profile</a>
			<a href="/logout">Log Out</a>
		</span>
	</div>
	<div id="main_wrapper">
		{% cms_toolbar %}
		{% show_menu 0%}
	 	{% placeholder base_content %}
		{% block base_content%}{% endblock %}
		{% render_block "js" %}
	</div>
</body>
</html>

MembershipSite/templates/edit_profile.html
{% load cms_tags sekizai_tags %}
<html>
<head>
	<title>Edit Profile</title>
	{% render_block "css" %}
</head>
<body>
	<h1>This is "Profile Edit" Page</h1>
	<form method="post" action="/editprofile/">
		{% csrf_token %}
		<label for="id_title">{{ form.title.label }}</label> {{ form.title }}{{form.title.errors}}<br/>
		<label for="id_username">{{ form.username.label }}</label> {{ form.username }}{{form.username.errors}}<br/>
		<label for="id_email">{{ form.email.label }}</label> {{ form.email }}{{form.email.errors}}<br/>
		<label for="id_password1">{{ form.password.label }}</label> {{ form.password }}<br/>
		<label for="id_password2">{{ form.confirm_password.label }}</label> {{ form.confirm_password }} {{form.confirm_password.errors}}<br/>
		<label for="id_country">{{ form.country.label }}</label> {{ form.country }}{{form.country.errors}}<br/>
		<label for="id_state">{{ form.state.label }}</label> {{ form.state }}{{form.state.errors}}<br/>
		<label for="id_city">{{ form.city.label }}</label> {{ form.city }}{{form.city.errors}}<br/>
		<a href="/main">Cancel</a>
		<input type="submit" value="Update Profile">
	</form>
	{% render_block "js" %}
</body>

MembershipSite/templates/email_confirmation.html
<html>
<head>
	<title>Congratulations</title>
</head>
<body>
	<p> Dear Sir/Madam </p>
	
	<p> You're registered in Officesecy.org</p>
	
	<p> If you want to login, then</p><a href="www.officesecy.org">click here</a>
</body>

MembershipSite/templates/email_from_admin.html
<html>
<head>
	<title>Message from Site</title>
</head>
<body>
	<p> Dear Sir/Madam </p>
	
	<p> This mail was sent from Officesecy.org admin</p>
	
	<p> Thanks for your help </p>
</body>

MembershipSite/templates/home.html
{% load cms_tags sekizai_tags %}
{% load menu_tags %}
<html>
<head>
	<title>{% page_attribute "page_title" %}</title>
	<style type="text/css">
		#header_wrapper{
			width : 100%;
			height : 100px;
			position: relative;
		}
	</style>
	{% render_block "css" %}
</head>
<body>
	{% if user.is_authenticated %}
		<div id="header_wrapper">
			<span style="position:absolute; left:30px; bottom:30px;">
				Username: {{ request.user.username }},
				EmailAddress: {{request.user.email }}
			</span>
			<span style="position:absolute; right:30px; bottom: 30px;"> 
				<a href="/editprofile">Edit Profile</a>
				<a href="/logout">Log Out</a>
			</span>
		</div>
	{% else %}
		<div id="header_wrapper">
			<span style="position:absolute; right:30px; bottom: 30px;"> 
				<a href="\login">Login</a>
				<a href="\registration">Sign in</a>
			</span>
		</div>
	{% endif %}
	{% show_menu 0%}
 	{% placeholder base_content %}
	{% block base_content%}{% endblock %}
	{% if user.is_authenticated %}
		{% placeholder home_content %}
	{% endif %}
	{% render_block "js" %}
</body>
</html>

MembershipSite/templates/login.html
{% load cms_tags sekizai_tags %}
<html>
<head>
	<title>Log In</title>
	{% render_block "css" %}
</head>
<body>
	<h1>This is "Login" Page</h1>
	
	<form method="post" action="/login/">
		{% csrf_token %}
		<label for="id_username"> {{ form.username.label }}</label> {{form.username}}<br/>
		<label for="id_password"> {{ form.password.label }}</label> {{form.password}}<br/>
		<a href="/">Cancel</a>
		<input type="submit" value="Continue"><br/>
	</form>
	{% render_block "js" %}
</body>

MembershipSite/templates/login_failed.html
{% load cms_tags sekizai_tags %}
<html>
<head>
	<title>Try Again</title>
	{% render_block "css" %}
</head>
<body>
	<h1>Login Failed : Your Username or Password is wrong</h1>
	<a href="/">Cancel</a>
	<a href="/login">Try Again</a>
	{% render_block "js" %}
</body>

MembershipSite/templates/registration.html
{% load cms_tags sekizai_tags %}
<html>
<head>
	<title>Registration</title>
	{% render_block "css" %}
</head>
<body>
	<h1>This is "Registration" Page</h1>
	<form method="post" action="/registration/">
		{% csrf_token %}
		<label for="id_title">{{ form.title.label }}</label> {{ form.title }}{{form.title.errors}}<br/>
		<label for="id_username">{{ form.username.label }}</label> {{ form.username }}{{form.username.errors}}<br/>
		<label for="id_email">{{ form.email.label }}</label> {{ form.email }}{{form.email.errors}}<br/>
		<label for="id_password1">{{ form.password.label }}</label> {{ form.password }}<br/>
		<label for="id_password2">{{ form.confirm_password.label }}</label> {{ form.confirm_password }} {{form.confirm_password.errors}}<br/>
		<label for="id_country">{{ form.country.label }}</label> {{ form.country }}{{form.country.errors}}<br/>
		<label for="id_state">{{ form.state.label }}</label> {{ form.state }}{{form.state.errors}}<br/>
		<label for="id_city">{{ form.city.label }}</label> {{ form.city }}{{form.city.errors}}<br/>
		<a href="/">Cancel</a>
		<input type="submit" value="Create account">
	</form>
	{% render_block "js" %}
</body>

MembershipSite/templates/registration_success.html
{% load cms_tags sekizai_tags %}
{% load menu_tags %}
<html>
<head>
	<title>Congratulation!</title>
	{% render_block "css" %}
</head>
<body>
	{% cms_toolbar %}
	<h1>Thank you!<h1>
	Please <a href="\login">Login</a> here
 	{% render_block "js" %}
</body>
</html>

MembershipSite/templates/template_1.html
{% extends "base.html" %}
{% load cms_tags sekizai_tags i18n menu_tags %}

{% block base_content %}
	
	{% placeholder template_1_content %}
	
{% endblock %}

MembershipSite/templates/template_2.html
{% extends "base.html" %}
{% load cms_tags sekizai_tags i18n menu_tags %}

{% block base_content %}
	<ul>
		{% show_menu 1 100 100 100 %}
	</ul>
    <h1>This is second template</h1>
	{% placeholder template_2_content %}
{% endblock %}

MembershipSite/templates/template_main.html
{% extends "base.html" %}
{% load cms_tags sekizai_tags i18n menu_tags %}
{% block base_content %}	
	
	{% placeholder main_content1 %}
	
{% endblock %}